# Generated by Django 4.0.4 on 2022-05-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_bookinformation_delete_information_delete_studetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookinformation',
            new_name='bookinfo',
        ),
    ]
